@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Fri Nov 09 23:09:34 +0800 2018
=======
REM Generated by Vivado on Fri Nov 09 21:44:32 +0800 2018
>>>>>>> eafa11a8ed896268e7471b72eaf16957843798c3
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim test_behav -key {Behavioral:sim_1:Functional:test} -tclbatch test.tcl -view E:/coding/verilog/Verilog/example6.2_4choose1/test_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
