# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/coding/Verilog/dram_20190908_2/dram_20190908_2.srcs/sources_1/ip/distributed_ram/distributed_ram.xci
# IP: The module: 'distributed_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/coding/Verilog/dram_20190908_2/dram_20190908_2.srcs/sources_1/ip/distributed_ram/distributed_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'distributed_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/coding/Verilog/dram_20190908_2/dram_20190908_2.srcs/sources_1/ip/distributed_ram/distributed_ram.xci
# IP: The module: 'distributed_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/coding/Verilog/dram_20190908_2/dram_20190908_2.srcs/sources_1/ip/distributed_ram/distributed_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'distributed_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
